version: '3.9'
services:
    postgres:
      image: postgres
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - 5432:5432

    sqlpad:
      image: sqlpad/sqlpad:7
      restart: always
      environment:
        SQLPAD_ADMIN: 'admin'
        SQLPAD_ADMIN_PASSWORD: 'admin'
        SQLPAD_APP_LOG_LEVEL: debug
        SQLPAD_WEB_LOG_LEVEL: warn
        SQLPAD_CONNECTIONS__pgdemo__name: Postgres demo
        SQLPAD_CONNECTIONS__pgdemo__driver: postgres
        SQLPAD_CONNECTIONS__pgdemo__host: postgres
        SQLPAD_CONNECTIONS__pgdemo__database: postgres
        SQLPAD_CONNECTIONS__pgdemo__username: postgres
        SQLPAD_CONNECTIONS__pgdemo__password: postgres
        SQLPAD_CONNECTIONS__pgdemo__multiStatementTransactionEnabled: 'true'
        SQLPAD_CONNECTIONS__pgdemo__idleTimeoutSeconds: 86400
      ports:
        - 3000:3000
